title: He Jiayang's Homepage
page-top-title: He Jiayang
top-section-bg-text: Intelligence Science & Technology
home-subtitle: He Jiayang&ensp;|&ensp;何家阳
copyright-text: '&copy; He Jiayang 2024-2025. All Rights Reserved.'
